project:
  type: website
  output-dir: docs

website:
  title: "MBA Portfolio – Carlos A"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true

editor: visual

